<?php
namespace Aosom\Marketing\Model;

use Magento\Framework\Model\AbstractModel;
use Aosom\Marketing\Api\Data\TestreportInterface;

class Testreport extends AbstractModel implements TestreportInterface,\Magento\Framework\DataObject\IdentityInterface
{
    const  CACHE_TAG = 'marketing_testreport';

    public $_cacheTag = self::CACHE_TAG;

    /**
     * @inheritdoc
     */
    protected function _construct()
    {
        $this->_init('Aosom\Marketing\Model\ResourceModel\Testreport');
    }



    public function getIdentities()
    {
        $identities = [self::CACHE_TAG . '_' . $this->getId()];

        //  $identities[] = self::CACHE_TAG;

        return array_unique($identities);
    }


    public function afterSave()
    {

        return parent::afterSave(); // TODO: Change the autogenerated stub
    }

    public function getEmail()
    {
        return $this->getData(self::EMAIL);
    }

    public function setEmail($email)
    {
        return $this->setData(self::EMAIL, $email);
    }

    public function getOrderId()
    {
        return $this->getData(self::ORDER_ID);
    }

    public function setOrderId($order_id)
    {
        return $this->setData(self::ORDER_ID, $order_id);
    }

    public function getPcBrowserExplain()
    {
        return $this->getData(self::PC_BROWSER_EXPLAIN);
    }

    public function setPcBrowserExplain($pc_browser_explain)
    {
        return $this->setData(self::PC_BROWSER_EXPLAIN, $pc_browser_explain);
    }

    public function getMobileBrandExplain()
    {
        return $this->getData(self::MOBILE_BEAND_EXPLAIN);
    }

    public function setMobileBrandExplain($mobile_brand_explain)
    {
        return $this->setData(self::MOBILE_BEAND_EXPLAIN, $mobile_brand_explain);
    }

    public function getTabletBrandExplain()
    {
        return $this->getData(self::TABLET_BEAND_EXPLAIN);
    }

    public function setTabletBrandExplain($tablet_brand_explain)
    {
        return $this->setData(self::TABLET_BEAND_EXPLAIN, $tablet_brand_explain);
    }

    public function getProblemPageDescription()
    {
        return $this->getData(self::PROBLEM_PAGE_DESCRIPTION);
    }

    public function setProblemPageDescription($problem_page_description)
    {
        return $this->setData(self::PROBLEM_PAGE_DESCRIPTION, $problem_page_description);
    }

    public function getSuggestions()
    {
        return $this->getData(self::SUGGESTIONS);
    }

    public function setSuggestions($suggestions)
    {
        return $this->setData(self::SUGGESTIONS, $suggestions);
    }

    public function getPcBrowser()
    {
        return $this->getData(self::PC_BROWSER);
    }

    public function setPcBrowser($pc_browser)
    {
        return $this->setData(self::PC_BROWSER, $pc_browser);
    }

    public function getMobileBrand()
    {
        return $this->getData(self::MOBILE_BRAND);
    }

    public function setMobileBrand($mobile_brand)
    {
        return $this->setData(self::MOBILE_BRAND, $mobile_brand);
    }

    public function getTabletBrand()
    {
        return $this->getData(self::TABLET_BEAND);
    }

    public function setTabletBrand($tablet_brand)
    {
        return $this->setData(self::TABLET_BEAND, $tablet_brand);
    }

    public function getLoadingSpeed()
    {
        return $this->getData(self::LOADING_SPEED);
    }

    public function setLoadingSpeed($loading_speed)
    {
        return $this->setData(self::LOADING_SPEED, $loading_speed);
    }

    public function getUi()
    {
        return $this->getData(self::UI);
    }

    public function setUi($ui)
    {
        return $this->setData(self::UI, $ui);
    }

    public function getSearching()
    {
        return $this->getData(self::SEARCHING);
    }

    public function setSearching($searching)
    {
        return $this->setData(self::SEARCHING, $searching);
    }

    public function getCategory()
    {
        return $this->getData(self::CATEGORY);
    }

    public function setCategory($category)
    {
        return $this->setData(self::CATEGORY, $category);
    }

    public function getPromotions()
    {
        return $this->getData(self::PROMORTIONS);
    }

    public function setPromotions($promotions)
    {
        return $this->setData(self::PROMORTIONS, $promotions);
    }

    public function getTextInput()
    {
        return $this->getData(self::TEXT_INPUT);
    }

    public function setTextInput($text_input)
    {
        return $this->setData(self::TEXT_INPUT, $text_input);
    }

    public function getPaymentMethod()
    {
        return $this->getData(self::PAYMENT_METHOD);
    }

    public function setPaymentMethod($payment_method)
    {
        return $this->setData(self::PAYMENT_METHOD, $payment_method);
    }

    public function getPaymentProcess()
    {
        return $this->getData(self::PAYMENT_PROCESS);
    }

    public function setPaymentProcess($payment_process)
    {
        return $this->setData(self::PAYMENT_PROCESS, $payment_process);
    }

    public function getStatus()
    {
        return $this->getData(self::STATUS);
    }

    public function setStatus($status)
    {
        return $this->setData(self::STATUS, $status);
    }

    public function getCreatedAt()
    {
        return $this->getData(self::CREATION_AT);
    }

    public function setCreatedAt($created_at)
    {
        return $this->setData(self::CREATION_AT, $created_at);
    }
}
