<?php
namespace Aosom\Marketing\Model;

use Magento\Framework\Model\AbstractModel;
use Aosom\Marketing\Api\Data\TrialInterface;

class Trial extends AbstractModel implements TrialInterface,\Magento\Framework\DataObject\IdentityInterface
{
    const  CACHE_TAG = 'marketing_trial';

    public $_cacheTag = self::CACHE_TAG;

    /**
     * @inheritdoc
     */
    protected function _construct()
    {
        $this->_init('Aosom\Marketing\Model\ResourceModel\Trial');
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getData(self::TRIAL_ID);
    }

    /**
     * @inheritdoc
     */
    public function setTrialId($trial_id)
    {
        return $this->setData(self::TRIAL_ID, $trial_id);
    }

    /**
     * @inheritdoc
     */
    public function getTitle()
    {
        return $this->getData(self::TITLE);
    }
    /**
     * @inheritdoc
     */
    public function setTitle($title)
    {
        return $this->setData(self::TITLE, $title);
    }

    /**
     * @inheritdoc
     */
    public function getVideo()
    {
        return $this->getData(self::VIDEO);
    }
    /**
     * @inheritdoc
     */
    public function setVideo($video)
    {
        return $this->setData(self::VIDEO, $video);
    }

    /**
     * @inheritdoc
     */
    public function getCustomerId()
    {
        return $this->getData(self::CUSTOMER_ID);
    }
    /**
     * @inheritdoc
     */
    public function setCustomerId($customer_id)
    {
        return $this->setData(self::CUSTOMER_ID, $customer_id);
    }
    /**
     * @inheritdoc
     */
    public function getOrderId()
    {
        return $this->getData(self::INCREMENT_ID);
    }
    /**
     * @inheritdoc
     */
    public function setOrderId($order_id)
    {
        return $this->setData(self::INCREMENT_ID, $order_id);
    }
    /**
     * @inheritdoc
     */
    public function getProductId()
    {
        return $this->getData(self::PRODUCT_ID);
    }
    /**
     * @inheritdoc
     */
    public function setProductId($product_id)
    {
        return $this->setData(self::PRODUCT_ID, $product_id);
    }
    /**
     * @inheritdoc
     */
    public function getCustomerName()
    {
        return $this->getData(self::CUSTOMER_NAME);
    }
    /**
     * @inheritdoc
     */
    public function setCustomerName($customer_name)
    {
        return $this->setData(self::CUSTOMER_NAME, $customer_name);
    }
    /**
     * @inheritdoc
     */
    public function getContent()
    {
        return $this->getData(self::CONTENT);
    }
    /**
     * @inheritdoc
     */
    public function setContent($content)
    {
        return $this->setData(self::CONTENT, $content);
    }
    /**
     * @inheritdoc
     */
    public function getImgs()
    {
        return $this->getData(self::IMGS);
    }
    /**
     * @inheritdoc
     */
    public function setImgs($imgs)
    {
        return $this->setData(self::IMGS, $imgs);
    }
    /**
     * @inheritdoc
     */
    public function getStatus()
    {
        return $this->getData(self::STATUS);
    }
    /**
     * @inheritdoc
     */
    public function setStatus($status)
    {
        return $this->setData(self::STATUS, $status);
    }

    /**
     * @inheritdoc
     */
    public function getCreatedAt()
    {
        return $this->getData(self::CREATION_AT);
    }

    /**
     * @inheritdoc
     */
    public function setCreatedAt($creationAt)
    {
        return $this->setData(self::CREATION_AT, $creationAt);
    }

    /**
     * @inheritdoc
     */
    public function getUpdatedAt()
    {
        return $this->getData(self::UPDATE_AT);
    }

    /**
     * @inheritdoc
     */
    public function setUpdatedAt($updateAt)
    {
        return $this->setData(self::UPDATE_AT, $updateAt);
    }

    public function getIdentities()
    {
        $identities = [self::CACHE_TAG . '_' . $this->getId()];

        //  $identities[] = self::CACHE_TAG;

        return array_unique($identities);
    }


    public function afterSave()
    {

        return parent::afterSave(); // TODO: Change the autogenerated stub
    }

}
